### ISSUE TITLE
PA API 5.0?

### ISSUE THREAD

**Issue by Ed-MacDonald** [tinohager/Nager.AmazonProductAdvertising#99]
Do you have plans to update to PA API 5.0?  Apparently PA API 4.0 will stop working October 31.

**Comment by tinohager** [comment]
Hi, I'm just a little surprised they're shutting down the existing API so fast.

Yes i plan an update.

Documentation
https://webservices.amazon.com/paapi5/documentation/migration-guide/whats-new-in-paapi5.html

**Comment by Ed-MacDonald** [comment]
Thanks Tino.  Yea, I was quite surprised how little notice was given, especially going into the Q4 shopping season.

**Comment by ejjpi** [comment]
Am I the only one not seeing any actual improvement with the new API?
All I can see it's just an opportunity for Amazon to shrink its userbase and save infrastructure costs.
Shame

**Comment by tinohager** [comment]
What annoys me is the bad communication for the migration and the early shutdown date for the old API.

I've noticed so far:
- Json instead of xml
- Remove Cart Support, but I think that make sense
- Change AwsSignatureVersion from 2 to 4
- Missing EditorialReview -> Documentation info: Check back later for updates! The old api stop but check later?

**Comment by tinohager** [comment]
new package is available [nuget](https://www.nuget.org/packages/Nager.AmazonProductAdvertising/2.0.0)

**Comment by ElanHasson** [comment]
This doesn't seem to be working:

```
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate) in E:\A\_work\120\s\corefx\src\System.Linq\src\System\Linq\AnyAll.cs:line 28
   at Nager.AmazonProductAdvertising.AmazonResourceValidator.<>c__DisplayClass2_0.<IsResourcesValid>b__0(KeyValuePair`2 resource) in C:\Users\elan\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\4D9E2908-A032-45B5-9838-2991798D7523\18\ec1eaa5f\AmazonResourceValidator.cs:line 285
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate) in E:\A\_work\120\s\corefx\src\System.Linq\src\System\Linq\Count.cs:line 66
   at Nager.AmazonProductAdvertising.AmazonResourceValidator.IsResourcesValid(String[] resources, String operation) in C:\Users\elan\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\4D9E2908-A032-45B5-9838-2991798D7523\18\ec1eaa5f\AmazonResourceValidator.cs:line 285
   at Nager.AmazonProductAdvertising.AmazonProductAdvertisingClient.<GetItemsAsync>d__11.MoveNext() in C:\Users\elan\AppData\Local\JetBrains\Shared\vAny\DecompilerCache\decompiler\4D9E2908-A032-45B5-9838-2991798D7523\b4\dcc2a4b7\AmazonProductAdvertisingClient.cs:line 219
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in 
```

**Comment by tinohager** [comment]
@ElanHasson without a resources?

**Comment by ElanHasson** [comment]
Yes, there are two method overloads, one has resources parameter, one does not.

I tried passing resources and it failed to even try to contact the API. I get this exception above when I don't pass a resources parameter.

**Comment by tinohager** [comment]
@ElanHasson Check the new version please and check the ErrorMessage on response model

**Comment by ElanHasson** [comment]
Will do. I'll let you know how it goes.

**Comment by tinohager** [comment]
@ElanHasson Please also verify you are using the correct Endpoint end a valid partnerTag

**Comment by ejjpi** [comment]
Btw, how do you deal with request throttling? New requests limits are insanely low, only big websites with massive revenues can keep a decent quantity of products updated...

**Comment by Ed-MacDonald** [comment]
When I do a search for "harry potter books" I get an exception:

> Could not convert string to DateTime: 1997T. Path 'SearchResult.Items[9].ItemInfo.ContentInfo.PublicationDate.DisplayValue', line 1, position 82872.

```
   at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Nager.AmazonProductAdvertising.AmazonProductAdvertisingClient.<SearchItemsAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Nager.AmazonProductAdvertising.AmazonProductAdvertisingClient.<SearchItemsAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by tinohager** [comment]
> When I do a search for "harry potter books" I get an exception:
> 
> > Could not convert string to DateTime: 1997T. Path 'SearchResult.Items[9].ItemInfo.ContentInfo.PublicationDate.DisplayValue', line 1, position 82872.
> 
> ```
>    at Newtonsoft.Json.JsonReader.ReadDateTimeString(String s)
>    at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
>    at Newtonsoft.Json.JsonTextReader.ReadAsDateTime()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
>    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
>    at Nager.AmazonProductAdvertising.AmazonProductAdvertisingClient.<SearchItemsAsync>d__9.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Nager.AmazonProductAdvertising.AmazonProductAdvertisingClient.<SearchItemsAsync>d__8.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
> ```

Can you post the response from amazon the json?

**Comment by Ed-MacDonald** [comment]
I didn’t see the raw json anywhere in the exception (I was specifically looking so I could post it).  I’m going to pull down your source today so I can see what’s going on.

**Comment by Ed-MacDonald** [comment]
Here's the offending json returned for ASIN `B01DMC29U6`
```
"PublicationDate":
{
  "DisplayValue": "1997T",
  "Label": "PublicationDate",
  "Locale": "en_US"
}
```

**Comment by tinohager** [comment]
Please check the new version
